/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mastercard.dmp.take.home;

// import org.junit.jupiter.api.Test;

import com.App;

// import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    // @Test 
    // void appHasAGreeting() {
    //     App classUnderTest = new App();
    //     assertTrue(null, "app should have a greeting");
    // }
}
